blog/urls.py
from django.conf.urls import url
from django.urls import path
from blog import views


app_name = 'blogTag'

urlpatterns = [

    path('home/', views.home, name='home'),
    path('games/', views.games, name='games'),
    path('review/', views.review, name='review'),
    path('blog/', views.blog, name='blog'),
    path('contact/', views.contact, name='contact'),
    path('game_single', views.game_single, name='game_single'),
]

end_game/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from blog import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    #path('accounts/', include('django.contrib.auth.urls')),
    path('blog/', include('blog.urls')),
    path('user_app/', include('user_app.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_app/urls.py
from django.urls import path
from user_app import views

app_name = 'user_appTag'

urlpatterns = [

    path('login', views.login, name='login'),
    path('signup', views.signup, name='signup'),
    path('logout', views.logout, name='logout'),
]

blog/models.py
from django.db import models

# Create your models here.

class UserInfo:
    name = str
    email = str
    image = str

class account(models.Model):
    name = models.CharField(max_length=100)
    img = models.ImageField(upload_to='pics')
    email = models.EmailField(blank=True)

user_app/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from blog.models import UserInfo, account


# Create your views here.
def home(request):
    count = User.objects.count()
    dict = account.objects.all()
#    user1 = UserInfo()
#    user1.name='Hasibur'
#    user1.email='hasibur@gmail.com'
#    user1.image = 'author.jpg'
 #   dict = [user1, user2]

    return render(request, 'blog/home.html', {'dict':dict, 'count': count})

def games(request):
    return render(request, 'blog/games.html')

def review(request):
    return render(request, 'blog/review.html')

def blog(request):
    return render(request, 'blog/blog.html')

def contact(request):
    return render(request, 'blog/contact.html')

def game_single(request):
    return render(request, 'blog/game-single.html')

user_app/views.py
from django.contrib.auth.models import User, auth
from django.shortcuts import render, redirect
from django.contrib import messages

# Create your views here.


def signup(request):
    if request.method == 'POST':
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        user_name = request.POST['username']
        email = request.POST['email']
        password1 = request.POST['password1']
        password2 = request.POST['password2']

        if user_name=='' or password1=='':
            messages.info(request, "At least enter username and password")
            return redirect('user_appTag:signup')
        else:
            if password1 == password2:
                if User.objects.filter(username=user_name).exists():
                    messages.info(request, "username already taken")
                    return redirect('user_appTag:signup')
                else:
                    user = User.objects.create_user(username=user_name, password=password1, email=email,
                                                    first_name=first_name, last_name=last_name)
                    user.save()
                    return redirect('home')
            else:
                messages.info(request, "Password Not matched!")
                return redirect('user_appTag:signup')

    else:
        return render(request, 'blog/signup.html')

def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password1']
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request,user)
            return redirect('home')
        else:
            messages.info( request,"wrong username/password !")
            return redirect('user_appTag:login')
    return render(request, 'blog/login.html')

def logout(request):
    auth.logout(request)
    return redirect('home')

templates/blog/blog.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx">
<head>
	<title>EndGam - Gaming Magazine Template</title>
	<meta charset="UTF-8">
	<meta name="description" content="EndGam Gaming Magazine Template">
	<meta name="keywords" content="endGam,gGaming, magazine, html">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- Favicon -->
	<link href="{% static 'img/favicon.ico' %}" rel="shortcut icon"/>

	<!-- Google Font -->
	<link href="https://fonts.googleapis.com/css?family=Roboto:400,400i,500,500i,700,700i,900,900i" rel="stylesheet">


	<!-- Stylesheets -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/animate.css' %}"/>

	<!-- Main Stylesheets -->
	<link rel="stylesheet" href="{% static 'css/style.css' %}"/>


	<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->

</head>
<body>
	<!-- Page Preloder -->
	<div id="preloder">
		<div class="loader"></div>
	</div>

	<!-- Header section -->
	<header class="header-section">
		<div class="header-warp">
			<div class="header-social d-flex justify-content-end">
				<p>Follow us:</p>
				<a href="#"><i class="fa fa-pinterest"></i></a>
				<a href="#"><i class="fa fa-facebook"></i></a>
				<a href="#"><i class="fa fa-twitter"></i></a>
				<a href="#"><i class="fa fa-dribbble"></i></a>
				<a href="#"><i class="fa fa-behance"></i></a>
			</div>
			<div class="header-bar-warp d-flex">
				<!-- site logo -->
				<a href="{% url 'blogTag:home' %}" class="site-logo">
					<img src="{% static './img/logo.png' %}" alt="">
				</a>
				<nav class="top-nav-area w-100">
					<div class="user-panel">
                        {% if user.is_authenticated %}
                         <a href="{% url 'blogTag:home' %}">Hello, {{ user.username }}</a> / <a href="{% url 'user_appTag:logout' %}">Log Out</a>
                        {% else %}
						<a href="{% url 'user_appTag:login' %}">Login</a> / <a href="{% url 'user_appTag:signup' %}">Register</a>
                        {% endif %}
					</div>
					<!-- Menu -->
					<ul class="main-menu primary-menu">
						<li><a href="{% url 'blogTag:home' %}">Home</a></li>
						<li><a href="{% url 'blogTag:games' %}">Games</a>
							<ul class="sub-menu">
								<li><a href="{% url 'blogTag:game_single' %}">Game Single</a></li>
							</ul>
						</li>
						<li><a href="{% url 'blogTag:review' %}">Reviews</a></li>
						<li><a href="{% url 'blogTag:blog' %}">News</a></li>
						<li><a href="{% url 'blogTag:contact' %}">Contact</a></li>
					</ul>
				</nav>
			</div>
		</div>
	</header>
	<!-- Header section end -->


	<!-- Page top section -->
	<section class="page-top-section set-bg" data-setbg="{% static 'img/page-top-bg/3.jpg' %}">
		<div class="page-info">
			<h2>Blog</h2>
			<div class="site-breadcrumb">
				<a href="">Home</a>  /
				<span>Blog</span>
			</div>
		</div>
	</section>
	<!-- Page top end-->


	<!-- Blog page -->
	<section class="blog-page">
		<div class="container">
			<div class="row">
				<div class="col-xl-9 col-lg-8 col-md-7">
					<ul class="blog-filter">
						<li><a href="#">Racing</a></li>
						<li><a href="#">Shooters</a></li>
						<li><a href="#">Strategy</a></li>
						<li><a href="#">Online</a></li>
					</ul>
					<div class="big-blog-item">
						<img src="{% static 'img/blog-big/1.jpg' %}" alt="#" class="blog-thumbnail">
						<div class="blog-content text-box text-white">
							<div class="top-meta">11.11.18  /  in <a href="">Games</a></div>
							<h3>The best VR games on the market</h3>
							<p>Lorem ipsum dolor sit amet consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.....</p>
							<a href="#" class="read-more">Read More <img src="{% static 'img/icons/double-arrow.png' %}" alt="#"/></a>
						</div>
					</div>
					<div class="big-blog-item">
						<img src="{% static 'img/blog-big/2.jpg' %}" alt="#" class="blog-thumbnail">
						<div class="blog-content text-box text-white">
							<div class="top-meta">11.11.18  /  in <a href="">Games</a></div>
							<h3>The best online game is out now!</h3>
							<p>Lorem ipsum dolor sit amet consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.....</p>
							<a href="#" class="read-more">Read More <img src="{% static 'img/icons/double-arrow.png' %}" alt="#"/></a>
						</div>
					</div>
					<div class="big-blog-item">
						<img src="{% static 'img/blog-big/3.jpg' %}" alt="#" class="blog-thumbnail">
						<div class="blog-content text-box text-white">
							<div class="top-meta">11.11.18  /  in <a href="">Games</a></div>
							<h3>The best online game is out now!</h3>
							<p>Lorem ipsum dolor sit amet consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.....</p>
							<a href="#" class="read-more">Read More <img src="{% static 'img/icons/double-arrow.png' %}" alt="#"/></a>
						</div>
					</div>
					<div class="site-pagination">
						<a href="#" class="active">01.</a>
						<a href="#">02.</a>
						<a href="#">03.</a>
					</div>
				</div>
				<div class="col-xl-3 col-lg-4 col-md-5 sidebar">
					<div id="stickySidebar">
						<div class="widget-item">
							<form class="search-widget">
								<input type="text">
								<button>search</button>
							</form>
						</div>
						<div class="widget-item">
							<h4 class="widget-title">Trending</h4>
							<div class="trending-widget">
								<div class="tw-item">
									<div class="tw-thumb">
										<img src="{% static './img/blog-widget/1.jpg' %}" alt="#">
									</div>
									<div class="tw-text">
										<div class="tw-meta">11.11.18  /  in <a href="">Games</a></div>
										<h5>The best online game is out now!</h5>
									</div>
								</div>
								<div class="tw-item">
									<div class="tw-thumb">
										<img src="{% static './img/blog-widget/2.jpg' %}" alt="#">
									</div>
									<div class="tw-text">
										<div class="tw-meta">11.11.18  /  in <a href="">Games</a></div>
										<h5>The best online game is out now!</h5>
									</div>
								</div>
								<div class="tw-item">
									<div class="tw-thumb">
										<img src="{% static './img/blog-widget/3.jpg' %}" alt="#">
									</div>
									<div class="tw-text">
										<div class="tw-meta">11.11.18  /  in <a href="">Games</a></div>
										<h5>The best online game is out now!</h5>
									</div>
								</div>
								<div class="tw-item">
									<div class="tw-thumb">
										<img src="{% static './img/blog-widget/4.jpg' %}" alt="#">
									</div>
									<div class="tw-text">
										<div class="tw-meta">11.11.18  /  in <a href="">Games</a></div>
										<h5>The best online game is out now!</h5>
									</div>
								</div>
							</div>
						</div>
						<div class="widget-item">
							<div class="categories-widget">
								<h4 class="widget-title">categories</h4>
								<ul>
									<li><a href="">Games</a></li>
									<li><a href="">Gaming Tips & Tricks</a></li>
									<li><a href="">Online Games</a></li>
									<li><a href="">Team Games</a></li>
									<li><a href="">Community</a></li>
									<li><a href="">Uncategorized</a></li>
								</ul>
							</div>
						</div>
						<div class="widget-item">
							<h4 class="widget-title">Latest Comments</h4>
							<div class="latest-comments">
								<div class="lc-item">
									<img src="{% static './img/blog-widget/1.jpg' %}" class="lc-avatar" alt="#">
									<div class="tw-text"><a href="">Maria Smith</a> <span>On</span> The best online game out there </div>
								</div>
								<div class="lc-item">
									<img src="{% static './img/blog-widget/2.jpg' %}" class="lc-avatar" alt="#">
									<div class="tw-text"><a href="">Maria Smith</a> <span>On</span> The best online game out there </div>
								</div>
								<div class="lc-item">
									<img src="{% static './img/blog-widget/3.jpg' %}" class="lc-avatar" alt="#">
									<div class="tw-text"><a href="">Maria Smith</a> <span>On</span> The best online game out there </div>
								</div>
								<div class="lc-item">
									<img src="{% static './img/blog-widget/4.jpg' %}" class="lc-avatar" alt="#">
									<div class="tw-text"><a href="">Maria Smith</a> <span>On</span> The best online game out there </div>
								</div>
							</div>
						</div>
						<div class="widget-item">
							<a href="#" class="add">
								<img src="{% static './img/add.jpg' %}" alt="">
							</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- Blog page end-->


	<!-- Newsletter section -->
	<section class="newsletter-section">
		<div class="container">
			<h2>Subscribe to our newsletter</h2>
			<form class="newsletter-form">
				<input type="text" placeholder="ENTER YOUR E-MAIL">
				<button class="site-btn">subscribe <img src="{% static 'img/icons/double-arrow.png' %}" alt="#"/></button>
			</form>
		</div>
	</section>
	<!-- Newsletter section end -->


	<!-- Footer section -->
	<footer class="footer-section">
		<div class="container">

			<div class="footer-right-pic">
				<img src="{% static 'img/footer-right-pic.png' %}" alt="">
			</div>
			<a href="#" class="footer-logo">
				<img src="{% static './img/logo.png' %}" alt="">
			</a>
			<ul class="main-menu footer-menu">
				<li><a href="">Home</a></li>
				<li><a href="">Games</a></li>
				<li><a href="">Reviews</a></li>
				<li><a href="">News</a></li>
				<li><a href="">Contact</a></li>
			</ul>
			<div class="footer-social d-flex justify-content-center">
				<a href="#"><i class="fa fa-pinterest"></i></a>
				<a href="#"><i class="fa fa-facebook"></i></a>
				<a href="#"><i class="fa fa-twitter"></i></a>
				<a href="#"><i class="fa fa-dribbble"></i></a>
				<a href="#"><i class="fa fa-behance"></i></a>
			</div>
			<div class="copyright"><a href="">Colorlib</a> 2018 @ All rights reserved</div>
		</div>
	</footer>
	<!-- Footer section end -->


	<!--====== Javascripts & Jquery ======-->
	<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/jquery.slicknav.min.js' %}"></script>
	<script src="{% static 'js/owl.carousel.min.js' %}"></script>
	<script src="{% static 'js/jquery.sticky-sidebar.min.js' %}"></script>
	<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
	<script src="{% static 'js/main.js' %}"></script>

	</body>
</html>

templates/blog/contact.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx">
<head>
	<title>EndGam - Gaming Magazine Template</title>
	<meta charset="UTF-8">
	<meta name="description" content="EndGam Gaming Magazine Template">
	<meta name="keywords" content="endGam,gGaming, magazine, html">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- Favicon -->
	<link href="{% static "img/favicon.ico" %}" rel="shortcut icon"/>

	<!-- Google Font -->
	<link href="https://fonts.googleapis.com/css?family=Roboto:400,400i,500,500i,700,700i,900,900i" rel="stylesheet">


	<!-- Stylesheets -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/animate.css' %}"/>

	<!-- Main Stylesheets -->
	<link rel="stylesheet" href="{% static 'css/style.css' %}"/>


	<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->

</head>
<body>
	<!-- Page Preloder -->
	<div id="preloder">
		<div class="loader"></div>
	</div>

	<!-- Header section -->
	<header class="header-section">
		<div class="header-warp">
			<div class="header-social d-flex justify-content-end">
				<p>Follow us:</p>
				<a href="#"><i class="fa fa-pinterest"></i></a>
				<a href="#"><i class="fa fa-facebook"></i></a>
				<a href="#"><i class="fa fa-twitter"></i></a>
				<a href="#"><i class="fa fa-dribbble"></i></a>
				<a href="#"><i class="fa fa-behance"></i></a>
			</div>
			<div class="header-bar-warp d-flex">
				<!-- site logo -->
				<a href="{% url 'blogTag:home' %}" class="site-logo">
					<img src="{% static './img/logo.png' %}" alt="">
				</a>
				<nav class="top-nav-area w-100">
					<div class="user-panel">
                        {% if user.is_authenticated %}
                         <a href="{% url 'blogTag:home' %}">Hello, {{ user.username }}</a> / <a href="{% url 'user_appTag:logout' %}">Log Out</a>
                        {% else %}
						<a href="{% url 'user_appTag:login' %}">Login</a> / <a href="{% url 'user_appTag:signup' %}">Register</a>
                        {% endif %}
					</div>
					<!-- Menu -->
					<ul class="main-menu primary-menu">
						<li><a href="{% url 'blogTag:home' %}">Home</a></li>
						<li><a href="{% url 'blogTag:games' %}">Games</a>
							<ul class="sub-menu">
								<li><a href="{% url 'blogTag:game_single' %}">Game Single</a></li>
							</ul>
						</li>
						<li><a href="{% url 'blogTag:review' %}">Reviews</a></li>
						<li><a href="{% url 'blogTag:blog' %}">News</a></li>
						<li><a href="{% url 'blogTag:contact' %}">Contact</a></li>
					</ul>
				</nav>
			</div>
		</div>
	</header>
	<!-- Header section end -->


	<!-- Page top section -->
	<section class="page-top-section set-bg" data-setbg="{% static 'img/page-top-bg/4.jpg' %}">
		<div class="page-info">
			<h2>Contact</h2>
			<div class="site-breadcrumb">
				<a href="">Home</a>  /
				<span>Contact</span>
			</div>
		</div>
	</section>
	<!-- Page top end-->


	<!-- Contact page -->
	<section class="contact-page">
		<div class="container">
			<iframe src="https://www.google.com/maps/embed?pb=!1m10!1m8!1m3!1d3644.1401095831125!2d90.3853464!3d24.0261239!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2sbd!4v1599408368873!5m2!1sen!2sbd" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
			<div class="row">
				<div class="col-lg-7 order-2 order-lg-1">
					<form class="contact-form">
						<input type="text" placeholder="Your name">
						<input type="text" placeholder="Your e-mail">
						<input type="text" placeholder="Subject">
						<textarea placeholder="Message"></textarea>
						<button class="site-btn">Send message<img src="{% static 'img/icons/double-arrow.png' %}" alt="#"/></button>
					</form>
				</div>
			</div>
		</div>
	</section>
	<!-- Contact page end-->


	<!-- Newsletter section -->
	<section class="newsletter-section">
		<div class="container">
			<h2>Subscribe to our newsletter</h2>
			<form class="newsletter-form">
                <label>
                    <input type="text" placeholder="ENTER YOUR E-MAIL">
                </label>
                <button class="site-btn">subscribe  <img src="{% static 'img/icons/double-arrow.png' %}" alt="#"/></button>
			</form>
		</div>
	</section>
	<!-- Newsletter section end -->


	<!-- Footer section -->
	<footer class="footer-section">
		<div class="container">

			<div class="footer-right-pic">
				<img src="{% static 'img/footer-right-pic.png' %}" alt="">
			</div>
			<a href="#" class="footer-logo">
				<img src="{% static './img/logo.png' %}" alt="">
			</a>
			<ul class="main-menu footer-menu">
				<li><a href="">Home</a></li>
				<li><a href="">Games</a></li>
				<li><a href="">Reviews</a></li>
				<li><a href="">News</a></li>
				<li><a href="">Contact</a></li>
			</ul>
			<div class="footer-social d-flex justify-content-center">
				<a href="#"><i class="fa fa-pinterest"></i></a>
				<a href="#"><i class="fa fa-facebook"></i></a>
				<a href="#"><i class="fa fa-twitter"></i></a>
				<a href="#"><i class="fa fa-dribbble"></i></a>
				<a href="#"><i class="fa fa-behance"></i></a>
			</div>
			<div class="copyright"><a href="">Colorlib</a> 2018 @ All rights reserved</div>
		</div>
	</footer>
	<!-- Footer section end -->


	<!--====== Javascripts & Jquery ======-->
	<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/jquery.slicknav.min.js' %}"></script>
	<script src="{% static 'js/owl.carousel.min.js' %}"></script>
	<script src="{% static 'js/jquery.sticky-sidebar.min.js' %}"></script>
	<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
	<script src="{% static 'js/main.js' %}"></script>

	</body>
</html>

templates/blog/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<style>
    #loginbody {
        background: cyan;
        alignment: center;
    }
</style>
<body id="loginbody">
  <div>
      <form action="login" method="POST">
       {% csrf_token %}
          <div align="center">
              <h1 align="center">Log In</h1>
              <a href="{% url 'blogTag:home' %}">Home</a><hr>
              <div class="row justify-content-center">
                  <div class="form-group">
                      <label for="username">Username:</label>
                      <input type="text" name="username" placeholder="Enter Username" ><br>
                  </div>
                  <p></p>
                  <div class="form-group">
                      <label for="password">Password:</label>
                       <input type="password" name="password1" placeholder="Enter Password"><br>
                  </div>
              </div>
              <p></p>
              <input type="submit" placeholder="Login" class="btn btn-primary">
          </div>
   </form>
  </div>
<div class="form-group">
   <div align="center" style="background: red border-box">
       {% for message in messages %}
           <h2>{{ message }}</h2>
       {% endfor %}
   </div>

</body>
</html>

templates/blog/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sign Up</title>
</head>
<style>
    #signupbody {
        background: cyan;
        alignment: center;
    }
</style>
<body id="signupbody">
  <div>
      <form action="signup" method="POST">
       {% csrf_token %}
          <div align="center">
              <h1 align="center">Sign Up</h1>
              <a href="{% url 'blogTag:home' %}">Home</a><hr>
              <input type="text" name="first_name" placeholder="First Name"><br>
              <input type="text" name="last_name" placeholder="Last Name"><br>
              <input type="text" name="username" placeholder="Username" ><br>
              <input type="text" name="email" placeholder="Email"><br>
              <input type="password" name="password1" placeholder="Password"><br>
              <input type="password" name="password2" placeholder="Confirm Password"><br>
              <p></p>
              <input type="submit" placeholder="Sign up">
          </div>
   </form>
  </div>

   <div align="center" style="background: red border-box">
       {% for message in messages %}
           <h2>{{ message }}</h2>
       {% endfor %}
   </div>

</body>
</html>